name: smart_shoper_master
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  easy_localization: ^3.0.0
  flutter_lints: ^3.0.2
  flutter_screenutil: ^5.4.0+1
  flutter_svg: ^2.0.10+1
  flutter_custom_clippers: ^2.0.0
  pin_code_fields: ^8.0.1
  stop_watch_timer: ^3.1.1
  card_swiper: ^3.0.1
  google_maps_flutter: ^2.1.4
  dotted_line: ^3.1.0
  modal_bottom_sheet: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_bloc: ^8.1.5
  dio: ^5.3.0
  equatable: ^2.0.5
  awesome_dialog: ^3.1.0
  bloc: ^8.1.2
  logger: ^2.0.1
  path_provider: ^2.0.15
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  url_launcher: ^6.0.0
  sizer:
  toastification: ^1.2.1
  loading_animation_widget:
  firebase_messaging:
  firebase_core:
  flag:
  google_fonts: ^6.2.1
  flutter_launcher_icons: "^0.13.1"
  animated_text_kit: ^4.2.2
  flutter_rating_bar: ^4.0.1
  get_time_ago: ^1.3.1


flutter_icons:
  android: true
  ios: true
  image_path : "assets/images/logo.jpeg"



  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/
